

dependencies:
- appnope=0.1.0
- backports=1.0
- backports_abc=0.4
- decorator=4.0.10
- get_terminal_size
- ipykernel=4.4.1
- ipython=5.1.0
- ipython_genutils=0.1.0
- jupyter_client=4.3.0
- jupyter_core=4.1.1
- openssl=1.0.2h
- path.py=8.2.1
- pathlib2=2.1.0
- pexpect=4.0.1
- pickleshare=0.7.3
- pip=8.1.2
- prompt_toolkit=1.0.3
- ptyprocess=0.5.1
- pygments=2.1.3
- python=2.7.12
- python.app=1.2
- pyzmq=15.4.0
- readline=6.2=2
- setuptools=25.1.6
- simplegeneric=0.8.1
- singledispatch=3.4.0.3
- six=1.10.0
- sqlite=3.13.0
- ssl_match_hostname=3.4.0.2
- tk=8.5.18
- tornado=4.4.1
- traitlets=4.2.2
- wcwidth=0.1.7
- wheel=0.29.0
- zlib=1.2.8
- pip:
  - apptools==4.4.0
  - backports-abc==0.4
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.4.0.2
  - bottleneck==1.1.0
  - configobj==5.0.6
  - cycler==0.10.0
  - cytoflow==0.3.2
  - envisage==4.5.1
  - fcsparser==0.1.2
  - functools32==3.2.3.post2
  - ipython-genutils==0.1.0
  - jsonschema==2.5.1
  - jupyter-client==4.3.0
  - jupyter-core==4.1.1
  - matplotlib==1.5.1
  - nbformat==4.1.0
  - numexpr==2.6.1
  - numpy==1.11.1
  - pandas==0.18.1
  - prompt-toolkit==1.0.3
  - pyface==4.4.0
  - pyparsing==2.1.8
  - python-dateutil==2.5.3
  - pytz==2016.6.1
  - scikit-learn==0.17.1
  - scipy==0.18.0
  - seaborn==0.7.1
  - statsmodels==0.6.1
  - traits==4.5.0
  - traitsui==5.1.0


